steps:
  # Step 1: Install dependencies
  - name: "node:18"
    entrypoint: npm
    args: ["install"]

  # Step 2: Run build (optional)
  # - name: "node:18"
  #   entrypoint: npm
  #   args: ["run", "build"]

  # Step 3: Run tests (optional)
  # - name: "node:18"
  #   entrypoint: npm
  #   args: ["test"]

  # Step 4: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bloom-tales-backend", "."]

images:
  - "gcr.io/$PROJECT_ID/bloom-tales-backend"

# Optional: Set build timeout
timeout: "900s"

# 👇 Add this section to fix logging issue
options:
  logging: CLOUD_LOGGING_ONLY
